server:
  port: 8082
spring:
  dubbo:
    application:
      name: service-consumer
    base-package: com.lsnu #\u670D\u52A1\u63D0\u4F9B\u8005\u6240\u5728\u7684\u5305
    registry:
      address: 127.0.0.1  # zookeeper\u6CE8\u518C\u4E2D\u5FC3\u7684\u5730\u5740
      port: 2181              # zookeeper\u6CE8\u518C\u4E2D\u5FC3\u7684\u7AEF\u53E3
      protocol: zookeeper
      subscribe: true
    protocol:
      name: dubbo
      host: 127.0.0.1
    consumer:
      timeout: 1000
      check: false  # \u670D\u52A1\u542F\u52A8\u65F6\u68C0\u67E5\u88AB\u8C03\u7528\u670D\u52A1\u662F\u5426\u53EF\u7528
      retries: 2    # \u670D\u52A1\u8C03\u7528\u91CD\u8BD5\u6B21\u6570
